import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
  AiFillGithub,
  AiFillWechat,
} from "react-icons/ai";
import Image from "next/image";
import timothy from "../public/timothy.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import Services from "../components/services";
import Portfolio from "../components/Portfolio";
import Footer from "../components/footer";
import { projects } from "../constants/projects";
import { useState } from "react";
import { services } from "../constants/services";
import { FaWhatsapp } from "react-icons/fa";
import Modal from "../components/modal";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Akiode Timothy Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-2xl font-burtons lg:text-4xl dark:text-white">
              Timothy
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/1yUMJZeKXjtW0165nB3zfC4DxozNsM4XX/view?usp=sharing"
                  download="AkiodeTimothy_Resume.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center px-4 py-10 md:px-10">
            <h2 className="text-3xl md:text-6xl py-2 text-teal-500 font-medium">
              Akiode Timothy
            </h2>
            <h3 className="text-base md:text-2xl py-2 dark:text-white">
              {`Looking to elevate your tech game? Meet Akiode Timothy - the software engineer who's got all your bases covered! Whether you need a frontend developer to make your website sing, a backend developer to streamline your operations, or a mobile development whiz to create a killer app, Akiode's your guy. With skills in all areas, he's the ultimate triple threat for all your tech needs.`}
            </h3>
          </div>
          <div className="flex justify-center gap-5 md:gap-8 lg:gap-12 py-3 md:py-6 text-black dark:text-white">
            <a
              href="https://twitter.com/akiode_timothy"
              target="_blank"
              rel="noopener noreferrer"
              className="w-12 md:w-16"
            >
              <AiFillTwitterCircle className="h-12 w-10 md:h-14 md:w-12" />
            </a>
            <a
              href="https://www.linkedin.com/in/timothy-akiode-7b772a164/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillLinkedin className="h-10 w-8 md:h-14 md:w-12 " />
            </a>
            <a
              href="http://github.com/timbaron"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillGithub className="h-12 w-10 md:h-14 md:w-12" />
            </a>
            <a
              href="https://wa.me/2348149792957?text=Hello%20Timothy%2C%20my%20name%20is%20_______.%20I%20got%20your%20contact%20from%20your%20portfolio."
              target="_blank"
              rel="noopener noreferrer"
            >
              <FaWhatsapp className="h-12 w-10 md:h-14 md:w-12" />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 md:w-96 md:h-96 mt-10 md:mt-20 overflow-hidden">
            <Image
              src={timothy}
              alt="Timothy"
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>

        <section className="dark:text-white">
          <div className=" text-center">
            <h3 className="text-3xl py-1 text-center">Services I offer</h3>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Since the beginning of my journey as a software engineer and full stack
              developer, I have workded with several companies and built 
            </p> */}
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              I offer from a wide range of services, including mobile and web
              frontend and backend development.
            </p>
          </div>
          <div className="grid gap-10 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4 pb-8">
            {services.map((service) => (
              <Services
                key={service.id}
                title={service.title}
                description={service.description}
              />
            ))}
          </div>
        </section>

        <section className="dark:text-white">
          <div>
            <h3 className="text-4xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Since the beginning of my journey as a freelance designer and
              developer, I have done remote work for several companies. I have
              had the <span className="text-teal-500">pleasure</span> of working
              with clients from all over the world.
            </p>
          </div>
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-8"></div>

          <div className="grid gap-10 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4 pb-8">
            {projects.map((project) => (
              <>
                <Portfolio
                  key={project.id}
                  project={project}
                  isDrawerOpen={isOpen}
                  setIsDrawerOpen={setIsOpen}
                />                
              </>
            ))}
          </div>
        </section>
        
        <Footer />
      </main>
    </div>
  );
}
